### ISSUE TITLE
Does not load on Firefox

### ISSUE THREAD

**Issue by trych** [ffd8/P5LIVE#21]
Hi there! About to start my new class using p5.js and was looking into also using P5LIVE.

On Firefox 69.0 under macOS 10.13.6 the site stays with the initial spinning P5LIVE logo forever. Not sure what's going on. In the console, it gives me this:

![20190926-133032_Screenshot_Firefox](https://user-images.githubusercontent.com/9803905/65685251-dca8a480-e061-11e9-85ce-6dfeb197bcb2.png)

**Comment by ffd8** [comment]
Hey @trych ! Awesome you think of using it for your course on p5.js (partially why it was created!) I'm pretty sure this bug has been fixed in the 'develop' branch (along with a firefox bug that prevented importing sketches), which is neeearly ready to push to the master (lots of features added.. especially 'softCompile' for smooth updating of individual functions without reloading whole sketch) – but for that feature, it's slowed down the update to make sure it's as smooth as possible (catching as many instances where a hard vs soft-compile should be automatically done). This last week I started my new classes with it and walked everyone through installing nodejs + cloning this repo locally, so they could run the develop branch offline using NPM. (if you switch to the develop branch, you'll see the updated readme). Hope that helps + in future.. i plan to do smaller updates for small bug fixes.. just too much got updated over summer to do that. FYI, I suggest using Chrome for P5LIVE, especially when it comes to audio-reactive code.. the engine just seems to work smoother.

**Comment by ffd8** [comment]
@trych – FYI, just merged the develop branch into the master and it should work fine in Firefox now both online and offline (tested w/ v69.0.3 + v70.0). 

Just be sure that this option is unchecked in the Security preferences:

- [ ] Delete cookies and site data when Firefox is closed

Since sketches are only stored in the localStorage of the browser (otherwise, one needs to export/import entire sketches each session).

**Comment by trych** [comment]
Hm, it still does not load in Firefox for me. I have the security option unchecked.

These two errors still show up (the first one from my previous screenshot is now gone):
![20191023-115325_Screenshot_Firefox](https://user-images.githubusercontent.com/9803905/67381186-d12a9980-f58b-11e9-89e2-84ab2a3752fd.png)

**Comment by ffd8** [comment]
Strange... even with a `Force reload page` holding down `shift` while refreshing?

**Comment by trych** [comment]
Yes.

**Comment by trych** [comment]
And btw. version is 70.0 now, still under macOS 10.13.6.

**Comment by trych** [comment]
And sorry I always come up with such annoying issues. 🙈

**Comment by ffd8** [comment]
haha no prob – but very strange.. it must be a left over from having loaded it a while back?? i'd suggest trashing all localstorage for the site, particularly the `settings` – then do a reload and hopefully it builds the missing one??

**Comment by ffd8** [comment]
Hope you didn't already trash your settings?? – just implemented an if statement to catch that bug (it's definitely from having already loaded P5LIVE in the past before there was cocoding..). Hopefully you can give the page a load again (might need to do a force reload) and hopefully it will overwrite the settings with current ones.

**Comment by ffd8** [comment]
Aha.. luckily still have my old first version online, just loaded it in Firefox, then tried to load the current version = hit this bug 💩

Reopening and will figure out what's wrong....

**Comment by ffd8** [comment]
Hey I fixed the transition bug from an older version of P5LIVE (only thing that persists, is the colored lines behind the code aren't auto activating.. still need to fix this) – but you should be able to load it, then good to hit the `RESET P5LIVE` button once. (export sketches just incase you had anything there first)

**Comment by trych** [comment]
Yes, can confirm it's working now with a simple hard reload. Thanks for fixing this!
